healthstack:
  image: healthstacker/healthstack
  cpu_shares: 100
  mem_limit: 262144000
  environment:
    NODE_ENV: production
  ports:
    - "80:3000"
  links:
    - redis
redis:
  image: redis
  command: redis-server --requirepass reiDwPYv2T7oGVPVdCvbouV2wGLxtEOxVIWgj5jo1EJvywW6A6bffMju2HWyexUEk8zUtyag3x/5kiRb
  cpu_shares: 100
  mem_limit: 262144000
  ports: 
    - "6379:6379"