FROM node:10
ENV NODE_ENV production
ENV PORT 3000
ENV CENTRE_PASTEUR_YAOUNDE_BUCKET <INSERT-VALUE-HERE>
ENV AWS_ACCESS_KEY_ID <INSERT-VALUE-HERE>
ENV AWS_SECRET_ACCESS_KEY <INSERT-VALUE-HERE>
ENV REGION <INSERT-VALUE-HERE>
ENV SENDER_EMAIL <INSERT-VALUE-HERE>
ENV SESSION_SECRET <INSERT-VALUE-HERE>
ENV AFRICAS_TALKING_API_KEY <INSERT-VALUE-HERE>
ENV AFRICAS_TALKING_USERNAME <INSERT-VALUE-HERE>
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install
COPY . .
EXPOSE 3000
CMD npm start